FROM postgres:16.2

# Set Postgres version environment variables
ENV PG_MAJOR=16

# Add the official Postgres 16 APT repository
RUN apt-get update && apt-get install -y wget gnupg lsb-release && \
    echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list && \
    wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -

# Install Postgres 16 compatible dev packages + build tools
RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    postgresql-server-dev-16 \
    postgis \
    postgresql-16-postgis-3 \
    postgresql-16-postgis-3-scripts \
 && rm -rf /var/lib/apt/lists/*

# Clone and install pg  vector
RUN cd /tmp \
    && git clone --branch v0.8.0 https://github.com/pgvector/pgvector.git \
    && cd pgvector \
    && make PG_CONFIG=/usr/lib/postgresql/16/bin/pg_config \
    && make install PG_CONFIG=/usr/lib/postgresql/16/bin/pg_config \
    && mkdir -p /usr/share/postgresql/16/extension/ \
    && cp vector.control /usr/share/postgresql/16/extension/ \
    && cp sql/* /usr/share/postgresql/16/extension/ \
    && rm -rf /tmp/pgvector

